In [1]:
import pandas as pd
import numpy as np
import os
import re

In [2]:
# 파일 경로 리스트
paths = [
    './data/train/1_회원정보_train.parquet',
    './data/train/2_신용정보_train.parquet',
    './data/train/3_승인매출정보_train.parquet',
    './data/train/4_청구입금정보_train.parquet',
    './data/train/5_잔액정보_train.parquet',
    './data/train/6_채널정보_train.parquet',
    './data/train/7_마케팅정보_train.parquet',
    './data/train/8_성과정보_train.parquet',
]

In [3]:
df = pd.read_csv('./corr_output/전체_is_C_상관계수_통합.csv')

In [4]:
df

            feature   correlation        source
0              기준년월 -3.742538e-14  1_회원정보_train
1                ID  6.018434e-03  1_회원정보_train
2            남녀구분코드  1.400640e-02  1_회원정보_train
3                연령 -3.598251e-02  1_회원정보_train
4           Segment  9.841903e-01  1_회원정보_train
..              ...           ...           ...
867      변동률_잔액_B1M  1.711321e-02  8_성과정보_train
868  변동률_잔액_일시불_B1M  4.034841e-03  8_성과정보_train
869   변동률_잔액_CA_B1M  6.253987e-03  8_성과정보_train
870       혜택수혜율_R3M -4.328916e-04  8_성과정보_train
871       혜택수혜율_B0M  3.236856e-03  8_성과정보_train

[872 rows x 3 columns]

In [5]:
corr_df = df[df['correlation'].abs() >= 0.1]
corr_df

                feature  correlation          source
4               Segment     0.984190    1_회원정보_train
44          이용금액_R3M_신용    -0.102762    1_회원정보_train
48           _1순위카드이용금액    -0.140124    1_회원정보_train
81             카드이용한도금액    -0.140910    2_신용정보_train
82               CA한도금액    -0.129304    2_신용정보_train
107        카드이용한도금액_B1M    -0.142525    2_신용정보_train
108        카드이용한도금액_B2M    -0.143877    2_신용정보_train
167       이용금액_일시불_R12M    -0.126456  3_승인매출정보_train
168        이용금액_할부_R12M    -0.121260  3_승인매출정보_train
170    이용금액_할부_무이자_R12M    -0.142076  3_승인매출정보_train
175     최대이용금액_일시불_R12M    -0.100249  3_승인매출정보_train
176      최대이용금액_할부_R12M    -0.104213  3_승인매출정보_train
178  최대이용금액_할부_무이자_R12M    -0.106239  3_승인매출정보_train
206     이용금액_할부_무이자_R6M    -0.102730  3_승인매출정보_train
250             이용금액_해외    -0.101639  3_승인매출정보_train
251         쇼핑_도소매_이용금액    -0.129490  3_승인매출정보_train
280           납부_기타이용금액    -0.103437  3_승인매출정보_train
282         _1순위업종_이용금액    -0.117289  3_승인매출정보_train
284         _2순위업종_이용금액    -0.103907  3_승인매출정보_train
286         _3순위업종_이용금액    -0.107683  3_승인매출정보_train
290       _2순위쇼핑업종_이용금액    -0.121439  3_승인매출정보_train
302       _2순위여유업종_이용금액    -0.101949  3_승인매출정보_train
315        할부금액_3M_R12M    -0.127714  3_승인매출정보_train
331    할부금액_무이자_3M_R12M    -0.144743  3_승인매출정보_train
397       이용금액_오프라인_R6M    -0.142087  3_승인매출정보_train
401       이용금액_오프라인_R3M    -0.124872  3_승인매출정보_train
405       이용금액_오프라인_B0M    -0.140880  3_승인매출정보_train
493          정상청구원금_B0M    -0.177086  3_승인매출정보_train
495          정상입금원금_B0M    -0.172740  3_승인매출정보_train
497          정상청구원금_B2M    -0.184681  3_승인매출정보_train
499          정상입금원금_B2M    -0.176818  3_승인매출정보_train
501          정상청구원금_B5M    -0.203137  3_승인매출정보_train
503          정상입금원금_B5M    -0.184845  3_승인매출정보_train
536             청구금액_B0    -0.170664  4_청구입금정보_train
537            청구금액_R3M    -0.179483  4_청구입금정보_train
538            청구금액_R6M    -0.184793  4_청구입금정보_train
553        마일_적립포인트_R3M    -0.110356  4_청구입금정보_train
570     포인트_마일리지_환산_B0M    -0.110936  4_청구입금정보_train
620       잔액_할부_무이자_B0M    -0.121330    5_잔액정보_train
636        평잔_일시불_해외_3M    -0.101736    5_잔액정보_train
646        평잔_일시불_해외_6M    -0.124339    5_잔액정보_train

In [46]:
# 1. 상관계수 기준 필터링
corr_df = df[df['correlation'].abs() >= 0.1]

# 2. Segment 행 제거
corr_df = corr_df[corr_df['feature'] != 'Segment']

In [47]:
corr_df = corr_df[corr_df['feature'].str.strip() != 'Segment']

In [48]:
corr_df

                feature  correlation          source
44          이용금액_R3M_신용    -0.102762    1_회원정보_train
48           _1순위카드이용금액    -0.140124    1_회원정보_train
81             카드이용한도금액    -0.140910    2_신용정보_train
82               CA한도금액    -0.129304    2_신용정보_train
107        카드이용한도금액_B1M    -0.142525    2_신용정보_train
108        카드이용한도금액_B2M    -0.143877    2_신용정보_train
167       이용금액_일시불_R12M    -0.126456  3_승인매출정보_train
168        이용금액_할부_R12M    -0.121260  3_승인매출정보_train
170    이용금액_할부_무이자_R12M    -0.142076  3_승인매출정보_train
175     최대이용금액_일시불_R12M    -0.100249  3_승인매출정보_train
176      최대이용금액_할부_R12M    -0.104213  3_승인매출정보_train
178  최대이용금액_할부_무이자_R12M    -0.106239  3_승인매출정보_train
206     이용금액_할부_무이자_R6M    -0.102730  3_승인매출정보_train
250             이용금액_해외    -0.101639  3_승인매출정보_train
251         쇼핑_도소매_이용금액    -0.129490  3_승인매출정보_train
280           납부_기타이용금액    -0.103437  3_승인매출정보_train
282         _1순위업종_이용금액    -0.117289  3_승인매출정보_train
284         _2순위업종_이용금액    -0.103907  3_승인매출정보_train
286         _3순위업종_이용금액    -0.107683  3_승인매출정보_train
290       _2순위쇼핑업종_이용금액    -0.121439  3_승인매출정보_train
302       _2순위여유업종_이용금액    -0.101949  3_승인매출정보_train
315        할부금액_3M_R12M    -0.127714  3_승인매출정보_train
331    할부금액_무이자_3M_R12M    -0.144743  3_승인매출정보_train
397       이용금액_오프라인_R6M    -0.142087  3_승인매출정보_train
401       이용금액_오프라인_R3M    -0.124872  3_승인매출정보_train
405       이용금액_오프라인_B0M    -0.140880  3_승인매출정보_train
493          정상청구원금_B0M    -0.177086  3_승인매출정보_train
495          정상입금원금_B0M    -0.172740  3_승인매출정보_train
497          정상청구원금_B2M    -0.184681  3_승인매출정보_train
499          정상입금원금_B2M    -0.176818  3_승인매출정보_train
501          정상청구원금_B5M    -0.203137  3_승인매출정보_train
503          정상입금원금_B5M    -0.184845  3_승인매출정보_train
536             청구금액_B0    -0.170664  4_청구입금정보_train
537            청구금액_R3M    -0.179483  4_청구입금정보_train
538            청구금액_R6M    -0.184793  4_청구입금정보_train
553        마일_적립포인트_R3M    -0.110356  4_청구입금정보_train
570     포인트_마일리지_환산_B0M    -0.110936  4_청구입금정보_train
620       잔액_할부_무이자_B0M    -0.121330    5_잔액정보_train
636        평잔_일시불_해외_3M    -0.101736    5_잔액정보_train
646        평잔_일시불_해외_6M    -0.124339    5_잔액정보_train

In [49]:
from pipeline.preprocessing import merge_segment_df

In [50]:
# from pipeline.preprocessing import merge_segment_df

selected_columns = corr_df['feature'].tolist()

paths = [
    './data/train/1_회원정보_train.parquet',
    './data/train/2_신용정보_train.parquet',
    './data/train/3_승인매출정보_train.parquet',
    './data/train/4_청구입금정보_train.parquet',
    './data/train/5_잔액정보_train.parquet',
    './data/train/6_채널정보_train.parquet',
    './data/train/7_마케팅정보_train.parquet',
    './data/train/8_성과정보_train.parquet',
]


df = merge_segment_df(selected_columns, paths)

In [51]:
df

,ID,이용금액_R3M_신용,_1순위카드이용금액,카드이용한도금액,카드이용한도금액_B1M,CA한도금액,카드이용한도금액_B2M,최대이용금액_할부_무이자_R12M,이용금액_오프라인_B0M,이용금액_오프라인_R6M,...,이용금액_오프라인_R3M,청구금액_R6M,청구금액_B0,포인트_마일리지_환산_B0M,마일_적립포인트_R3M,청구금액_R3M,잔액_할부_무이자_B0M,평잔_일시불_해외_3M,평잔_일시불_해외_6M,Segment
0,TRAIN_000000,196,3681,19354,20805,7270,19723,0,4043,11097,...,4131,88693,12226,0,0,46588,962,0,0,D
1,TRAIN_000000,-1190,2529,19796,20858,6293,20805,0,3883,13568,...,4852,119419,15756,0,0,53336,936,0,0,D
2,TRAIN_000000,868,3948,19728,20757,6449,20858,0,3926,11681,...,11853,132269,15732,0,0,43715,868,0,0,D
3,TRAIN_000000,-367,3157,19724,20704,5990,20757,0,3906,15847,...,11715,92304,14227,0,0,45716,903,0,0,D
4,TRAIN_000000,-478,3048,19580,20690,5816,20704,0,3918,16603,...,11751,97254,13958,0,0,43918,876,0,0,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,TRAIN_399999,17914,7883,86823,70735,25757,72942,11223,0,27296,...,7257,28912,3282,0,0,16399,1986,0,0,E
2399996,TRAIN_399999,23693,11358,87079,72865,26818,70735,10340,0,23902,...,4537,42577,4265,0,0,10244,1665,0,0,E
2399997,TRAIN_399999,17381,8823,86125,74286,27543,72865,9689,0,11861,...,0,23976,4103,0,0,11651,1619,0,0,E
2399998,TRAIN_399999,20773,8078,85770,71252,27113,74286,8830,0,7257,...,0,26946,2177,0,0,10546,1317,0,0,E
2399999,TRAIN_399999,21463,6984,86094,70247,25133,71252,8207,0,4537,...,0,19948,3422,0,0,9704,1448,0,0,E

In [53]:
from pipeline.vif_tools import stepwise_vif_table

# 1. Segment가 A/B/C만 대상
abc_df = df[df['Segment'].isin(['A', 'B', 'C'])].copy()

# 2. is_C 생성 (C: 0, A/B: 1)
abc_df['is_C'] = (abc_df['Segment'].isin(['A', 'B'])).astype(int)

# 삭제 가능한 컬럼만 추림
drop_cols = [col for col in ['ID', '기준년월', 'Segment'] if col in abc_df.columns]
vif_df = abc_df.drop(columns=drop_cols)

# 4. 수치형 컬럼만 추출
numeric_df = vif_df.select_dtypes(include='number')

# 5. VIF 계산
vif_table, vif_log = stepwise_vif_table(
    df=numeric_df,
    min_cols=5,
    output_path="./result/vif_ab_vs_c.csv",
    log_path="./result/vif_ab_vs_c_removed_log.csv"
)

VIF 테이블 저장 완료: ./result/vif_ab_vs_c.csv
제거 로그 저장 완료: ./result/vif_ab_vs_c_removed_log.csv

In [54]:
df_vif = pd.read_csv('./result/vif_ab_vs_c.csv')

In [55]:
top_5 = df_vif[['Variable', '5개']].dropna()

In [58]:
top_5

         Variable        5개
0          CA한도금액  1.070562
5   _2순위여유업종_이용금액  1.071231
7            is_C  1.039478
8       납부_기타이용금액  1.099724
20  잔액_할부_무이자_B0M  1.031662

In [57]:
df_vif[['Variable', '6개']].dropna()

         Variable        6개
0          CA한도금액  1.112685
5   _2순위여유업종_이용금액  1.128984
7            is_C  1.041541
8       납부_기타이용금액  1.145617
19        이용금액_해외  1.206445
20  잔액_할부_무이자_B0M  1.034971

In [65]:
df_vif[['Variable', '17개']].dropna()

           Variable       17개
0            CA한도금액  1.246351
1       _1순위업종_이용금액  2.177325
5     _2순위여유업종_이용금액  1.266084
6       _3순위업종_이용금액  2.752593
7              is_C  1.064424
8         납부_기타이용금액  1.384613
9      마일_적립포인트_R3M  1.684379
10      쇼핑_도소매_이용금액  3.069324
13    이용금액_오프라인_R3M  2.878689
19          이용금액_해외  1.486162
20    잔액_할부_무이자_B0M  3.296514
23       정상입금원금_B5M  2.234969
27          청구금액_B0  3.519918
29         청구금액_R6M  3.559172
30  최대이용금액_일시불_R12M  2.110102
31   최대이용금액_할부_R12M  2.719253
39     할부금액_3M_R12M  3.491724

In [67]:
print(df_vif[['Variable', '17개']].dropna())

           Variable       17개
0            CA한도금액  1.246351
1       _1순위업종_이용금액  2.177325
5     _2순위여유업종_이용금액  1.266084
6       _3순위업종_이용금액  2.752593
7              is_C  1.064424
8         납부_기타이용금액  1.384613
9      마일_적립포인트_R3M  1.684379
10      쇼핑_도소매_이용금액  3.069324
13    이용금액_오프라인_R3M  2.878689
19          이용금액_해외  1.486162
20    잔액_할부_무이자_B0M  3.296514
23       정상입금원금_B5M  2.234969
27          청구금액_B0  3.519918
29         청구금액_R6M  3.559172
30  최대이용금액_일시불_R12M  2.110102
31   최대이용금액_할부_R12M  2.719253
39     할부금액_3M_R12M  3.491724

In [68]:
selected_columns = df_vif[['Variable', '17개']].dropna()['Variable'].tolist()

In [73]:
from pipeline.preprocessing import merge_segment_df

paths = [
    './data/train/1_회원정보_train.parquet',
    './data/train/2_신용정보_train.parquet',
    './data/train/3_승인매출정보_train.parquet',
    './data/train/4_청구입금정보_train.parquet',
    './data/train/5_잔액정보_train.parquet',
    './data/train/6_채널정보_train.parquet',
    './data/train/7_마케팅정보_train.parquet',
    './data/train/8_성과정보_train.parquet'
]

# 함수 실행
merged_df = merge_segment_df(selected_columns, paths)

# 결과 저장
merged_df.to_csv('./result/C_AB_VIF_col_17_with_segment.csv', encoding='utf-8-sig', index=False)

In [74]:
merged_df

,ID,CA한도금액,_3순위업종_이용금액,정상입금원금_B5M,할부금액_3M_R12M,최대이용금액_일시불_R12M,납부_기타이용금액,이용금액_해외,이용금액_오프라인_R3M,최대이용금액_할부_R12M,쇼핑_도소매_이용금액,_2순위여유업종_이용금액,_1순위업종_이용금액,청구금액_R6M,청구금액_B0,마일_적립포인트_R3M,잔액_할부_무이자_B0M,Segment
0,TRAIN_000000,7270,672,9205,4917,4906,44,0,4131,0,0,0,1928,88693,12226,0,962,D
1,TRAIN_000000,6293,734,11161,4049,5350,40,0,4852,0,0,0,2000,119419,15756,0,936,D
2,TRAIN_000000,6449,835,16705,3671,6009,44,0,11853,0,0,0,2052,132269,15732,0,868,D
3,TRAIN_000000,5990,897,15950,3371,5901,48,0,11715,0,0,0,2020,92304,14227,0,903,D
4,TRAIN_000000,5816,344,16718,3341,6257,44,0,11751,0,0,0,2027,97254,13958,0,876,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,TRAIN_399999,25757,844,3845,24150,5760,0,0,7257,11223,0,0,3595,28912,3282,0,1986,E
2399996,TRAIN_399999,26818,980,5697,26213,6233,0,0,4537,10340,0,0,3551,42577,4265,0,1665,E
2399997,TRAIN_399999,27543,669,3507,26699,6091,0,0,0,9689,0,0,3586,23976,4103,0,1619,E
2399998,TRAIN_399999,27113,802,3645,24547,4624,0,0,0,8830,0,0,3533,26946,2177,0,1317,E
2399999,TRAIN_399999,25133,894,3647,24004,4593,0,0,0,8207,0,0,2955,19948,3422,0,1448,E