### 기본 라이브러리

In [1]:
import pandas as pd
import glob

### 데이터 조회 함수

In [2]:
# 데이터 확인 함수

def get_data_spec(df):
    null_ratio = (df.isnull().mean() * 100).round(2)
    spec = pd.DataFrame({
        '변수명': df.columns,
        '데이터 타입': df.dtypes.values,
        '결측치 개수': df.isnull().sum().values,
        '결측치 비율': [f"{val}%" for val in null_ratio.values]
    })
    return spec

In [4]:
# 호출 예시
# spec_df = get_data_spec(df)

### 데이터프레임 생성

In [5]:
# 데이터 불러오기
# df1 = pd.read_parquet("./data/train/1_회원정보_train.parquet")
# df2 = pd.read_parquet("./data/train/2_신용정보_train.parquet")
df3 = pd.read_parquet("./data/train/3_승인매출정보_train.parquet")
# df4 = pd.read_parquet("./data/train/4_청구입금정보_train.parquet")
# df5 = pd.read_parquet("./data/train/5_잔액정보_train.parquet")
# df6 = pd.read_parquet("./data/train/6_채널정보_train.parquet")
# df7 = pd.read_parquet("./data/train/7_마케팅정보_train.parquet")
# df8 = pd.read_parquet("./data/train/8_성과정보_train.parquet")

### **train**

#### 1. 회원정보

In [ ]:
# 데이터 확인 함수 호출
spec_df = get_data_spec(df1)
spec_df

              변수명  데이터 타입  결측치 개수 결측치 비율
0            기준년월   int64       0   0.0%
1              ID  object       0   0.0%
2          남녀구분코드   int64       0   0.0%
3              연령  object       0   0.0%
4         Segment  object       0   0.0%
..            ...     ...     ...    ...
73  우수회원면제카드수_B0M  object       0   0.0%
74    기타면제카드수_B0M  object       0   0.0%
75         카드신청건수   int64       0   0.0%
76     Life_Stage  object       0   0.0%
77      최종카드발급경과월   int64       0   0.0%

[78 rows x 4 columns]

In [ ]:
df1.shape

(2400000, 78)

#### 2.신용정보

In [ ]:
# 데이터 확인 함수 호출
spec_df = get_data_spec(df2)
spec_df

               변수명   데이터 타입   결측치 개수 결측치 비율
0             기준년월    int64        0   0.0%
1               ID   object        0   0.0%
2           최초한도금액    int64        0   0.0%
3         카드이용한도금액    int64        0   0.0%
4           CA한도금액    int64        0   0.0%
5        일시상환론한도금액    int64        0   0.0%
6         월상환론한도금액    int64        0   0.0%
7        CA이자율_할인전  float64        0   0.0%
8        CL이자율_할인전  float64        0   0.0%
9     RV일시불이자율_할인전  float64        0   0.0%
10  RV현금서비스이자율_할인전  float64        0   0.0%
11          RV신청일자  float64  1951236  81.3%
12         RV약정청구율  float64        0   0.0%
13        RV최소결제비율  float64        0   0.0%
14   자발한도감액횟수_R12M   object        0   0.0%
15   자발한도감액금액_R12M    int64        0   0.0%
16      자발한도감액후경과월    int64        0   0.0%
17   강제한도감액횟수_R12M    int64        0   0.0%
18   강제한도감액금액_R12M    int64        0   0.0%
19      강제한도감액후경과월    int64        0   0.0%
20     한도증액횟수_R12M   object        0   0.0%
21     한도증액금액_R12M    int64        0   0.0%
22        한도증액후경과월    int64        0   0.0%
23        상향가능한도금액    int64        0   0.0%
24      상향가능CA한도금액    int64        0   0.0%
25         카드론동의여부   object        0   0.0%
26    월상환론상향가능한도금액    int64        0   0.0%
27        RV전환가능여부   object    29473  1.23%
28   일시불ONLY전환가능여부    int64        0   0.0%
29    카드이용한도금액_B1M    int64        0   0.0%
30    카드이용한도금액_B2M    int64        0   0.0%
31    특별한도보유여부_R3M    int64        0   0.0%
32      연체감액여부_R3M    int64        0   0.0%
33        한도심사요청건수   object        0   0.0%
34        한도요청거절건수    int64        0   0.0%
35      한도심사요청후경과월    int64        0   0.0%
36      한도심사거절후경과월    int64        0   0.0%
37    시장단기연체여부_R6M    int64        0   0.0%
38    시장단기연체여부_R3M    int64        0   0.0%
39    시장연체상환여부_R6M    int64        0   0.0%
40    시장연체상환여부_R3M    int64        0   0.0%
41      rv최초시작후경과일    int64        0   0.0%

In [ ]:
df2.shape

(2400000, 42)

#### 3.승인매출정보

In [6]:
# 데이터 확인 함수 호출
spec_df = get_data_spec(df3)
spec_df

                 변수명  데이터 타입  결측치 개수 결측치 비율
0               기준년월   int64       0   0.0%
1                 ID  object       0   0.0%
2          최종이용일자_기본   int64       0   0.0%
3          최종이용일자_신판   int64       0   0.0%
4          최종이용일자_CA   int64       0   0.0%
..               ...     ...     ...    ...
401  승인거절건수_한도초과_R3M   int64       0   0.0%
402    승인거절건수_BL_R3M   int64       0   0.0%
403  승인거절건수_입력오류_R3M   int64       0   0.0%
404    승인거절건수_기타_R3M   int64       0   0.0%
405            이용금액대  object       0   0.0%

[406 rows x 4 columns]

In [7]:
df3.shape

(2400000, 406)

In [8]:
df3.isna().sum()

기준년월               0
ID                 0
최종이용일자_기본          0
최종이용일자_신판          0
최종이용일자_CA          0
                  ..
승인거절건수_한도초과_R3M    0
승인거절건수_BL_R3M      0
승인거절건수_입력오류_R3M    0
승인거절건수_기타_R3M      0
이용금액대              0
Length: 406, dtype: int64

In [9]:
null_cols = df3.columns[df3.isnull().any()]
df3[null_cols]

,_1순위업종,_2순위업종,_3순위업종,_1순위쇼핑업종,_2순위쇼핑업종,_3순위쇼핑업종,_1순위교통업종,_2순위교통업종,_3순위교통업종,_1순위여유업종,_2순위여유업종,_3순위여유업종,_1순위납부업종,_2순위납부업종,_3순위납부업종,최종카드론_금융상환방식코드,최종카드론_신청경로코드,최종카드론_대출일자
0,납부,쇼핑,사교활동,쇼핑기타,None,None,택시,버스지하철,None,None,None,None,보험료,납부기타,None,NaN,None,NaN
1,쇼핑,납부,교통,도소매,슈퍼마켓,편의점,주유,철도버스,None,None,None,None,통신비,None,None,5.0,8,20170327.0
2,쇼핑,사교활동,교통,온라인,도소매,마트,주유,None,None,None,None,None,None,None,None,5.0,8,20151119.0
3,쇼핑,납부,사교활동,마트,슈퍼마켓,None,택시,None,None,None,None,None,보험료,None,None,NaN,None,NaN
4,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN
2399996,쇼핑,의료,사교활동,도소매,슈퍼마켓,쇼핑기타,버스지하철,택시,None,None,None,None,납부기타,None,None,5.0,8,20170112.0
2399997,쇼핑,사교활동,교통,온라인,슈퍼마켓,쇼핑기타,주유,정비,None,운동,None,None,None,None,None,NaN,None,NaN
2399998,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN
2399999,쇼핑,의료,사교활동,백화점,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN

In [10]:
null_info = df3.isnull().sum()
null_info = null_info[null_info > 0]  # 결측치가 1개 이상인 컬럼만

# 비율도 같이 보기
null_ratio = (df3.isnull().mean() * 100)[null_info.index].round(2)

# DataFrame으로 보기 좋게 정리
pd.DataFrame({
    '결측치 개수': null_info,
    '결측치 비율(%)': null_ratio
})

                 결측치 개수  결측치 비율(%)
_1순위업종           539992      22.50
_2순위업종           912725      38.03
_3순위업종          1107898      46.16
_1순위쇼핑업종         922663      38.44
_2순위쇼핑업종        1135042      47.29
_3순위쇼핑업종        1312267      54.68
_1순위교통업종        1164494      48.52
_2순위교통업종        1656423      69.02
_3순위교통업종        2045455      85.23
_1순위여유업종        1987260      82.80
_2순위여유업종        2302286      95.93
_3순위여유업종        2377725      99.07
_1순위납부업종        1216263      50.68
_2순위납부업종        2033640      84.74
_3순위납부업종        2310187      96.26
최종카드론_금융상환방식코드  1958126      81.59
최종카드론_신청경로코드    1958226      81.59
최종카드론_대출일자      1988330      82.85

#### 4.청구입금정보

In [ ]:
spec_df = get_data_spec(df4)
spec_df

                 변수명  데이터 타입  결측치 개수 결측치 비율
0               기준년월   int64       0   0.0%
1                 ID  object       0   0.0%
2              대표결제일   int64       0   0.0%
3           대표결제방법코드  object       0   0.0%
4      대표청구지고객주소구분코드  object       0   0.0%
5       대표청구서수령지구분코드  object       0   0.0%
6            청구서수령방법  object       0   0.0%
7         청구서발송여부_B0   int64       0   0.0%
8        청구서발송여부_R3M   int64       0   0.0%
9        청구서발송여부_R6M   int64       0   0.0%
10           청구금액_B0   int64       0   0.0%
11          청구금액_R3M   int64       0   0.0%
12          청구금액_R6M   int64       0   0.0%
13   포인트_마일리지_건별_B0M   int64       0   0.0%
14   포인트_마일리지_건별_R3M   int64       0   0.0%
15    포인트_포인트_건별_B0M   int64       0   0.0%
16    포인트_포인트_건별_R3M   int64       0   0.0%
17  포인트_마일리지_월적립_B0M   int64       0   0.0%
18  포인트_마일리지_월적립_R3M   int64       0   0.0%
19   포인트_포인트_월적립_B0M   int64       0   0.0%
20   포인트_포인트_월적립_R3M   int64       0   0.0%
21    포인트_적립포인트_R12M   int64       0   0.0%
22     포인트_적립포인트_R3M   int64       0   0.0%
23    포인트_이용포인트_R12M   int64       0   0.0%
24     포인트_이용포인트_R3M   int64       0   0.0%
25     포인트_잔여포인트_B0M   int64       0   0.0%
26     마일_적립포인트_R12M   int64       0   0.0%
27      마일_적립포인트_R3M   int64       0   0.0%
28     마일_이용포인트_R12M   int64       0   0.0%
29      마일_이용포인트_R3M   int64       0   0.0%
30      마일_잔여포인트_B0M   int64       0   0.0%
31          할인건수_R3M  object       0   0.0%
32          할인금액_R3M   int64       0   0.0%
33          할인건수_B0M  object       0   0.0%
34          할인금액_B0M   int64       0   0.0%
35      할인금액_청구서_R3M   int64       0   0.0%
36      할인금액_청구서_B0M   int64       0   0.0%
37     상환개월수_결제일_R6M   int64       0   0.0%
38     상환개월수_결제일_R3M   int64       0   0.0%
39         선결제건수_R6M   int64       0   0.0%
40         선결제건수_R3M   int64       0   0.0%
41          연체건수_R6M   int64       0   0.0%
42          연체건수_R3M   int64       0   0.0%
43        혜택수혜금액_R3M   int64       0   0.0%
44   포인트_마일리지_환산_B0M   int64       0   0.0%
45            혜택수혜금액   int64       0   0.0%

In [ ]:
df4.shape

(2400000, 46)

#### 5.잔액정보

In [ ]:
spec_df = get_data_spec(df5)
spec_df

             변수명  데이터 타입  결측치 개수 결측치 비율
0           기준년월   int64       0   0.0%
1             ID  object       0   0.0%
2     잔액_일시불_B0M   int64       0   0.0%
3      잔액_할부_B0M   int64       0   0.0%
4   잔액_현금서비스_B0M   int64       0   0.0%
..           ...     ...     ...    ...
77      평잔_할부_6M   int64       0   0.0%
78   평잔_할부_해외_6M   int64       0   0.0%
79      평잔_CA_6M   int64       0   0.0%
80   평잔_CA_해외_6M   int64       0   0.0%
81     평잔_카드론_6M   int64       0   0.0%

[82 rows x 4 columns]

In [ ]:
df5.shape

(2400000, 82)

#### 6.채널정보

In [ ]:
spec_df = get_data_spec(df6)
spec_df

                변수명  데이터 타입   결측치 개수  결측치 비율
0              기준년월   int64        0    0.0%
1                ID  object        0    0.0%
2      인입횟수_ARS_R6M  object        0    0.0%
3    이용메뉴건수_ARS_R6M  object        0    0.0%
4      인입일수_ARS_R6M   int64        0    0.0%
..              ...     ...      ...     ...
100          OS구분코드  object  1633566  68.07%
101   홈페이지_금융건수_R6M   int64        0    0.0%
102  홈페이지_선결제건수_R6M   int64        0    0.0%
103   홈페이지_금융건수_R3M   int64        0    0.0%
104  홈페이지_선결제건수_R3M   int64        0    0.0%

[105 rows x 4 columns]

In [ ]:
df6.shape

(2400000, 105)

#### 7.마케팅정보

In [ ]:
spec_df = get_data_spec(df7)
spec_df

                변수명  데이터 타입  결측치 개수 결측치 비율
0              기준년월   int64       0   0.0%
1                ID  object       0   0.0%
2   컨택건수_카드론_TM_B0M   int64       0   0.0%
3   컨택건수_리볼빙_TM_B0M   int64       0   0.0%
4    컨택건수_CA_TM_B0M   int64       0   0.0%
..              ...     ...     ...    ...
59     컨택건수_FDS_B0M   int64       0   0.0%
60      컨택건수_채권_R6M   int64       0   0.0%
61     컨택건수_FDS_R6M   int64       0   0.0%
62     캠페인접촉건수_R12M  object       0   0.0%
63     캠페인접촉일수_R12M  object       0   0.0%

[64 rows x 4 columns]

In [ ]:
df7.shape

(2400000, 64)

#### 8.성과정보

In [ ]:
spec_df = get_data_spec(df8)
spec_df

                   변수명   데이터 타입  결측치 개수  결측치 비율
0                 기준년월    int64       0    0.0%
1                   ID   object       0    0.0%
2       증감율_이용건수_신용_전월  float64       0    0.0%
3       증감율_이용건수_신판_전월  float64       0    0.0%
4      증감율_이용건수_일시불_전월  float64       0    0.0%
5       증감율_이용건수_할부_전월  float64       0    0.0%
6       증감율_이용건수_CA_전월  float64       0    0.0%
7       증감율_이용건수_체크_전월  float64       0    0.0%
8      증감율_이용건수_카드론_전월  float64       0    0.0%
9       증감율_이용금액_신용_전월  float64       0    0.0%
10      증감율_이용금액_신판_전월  float64       0    0.0%
11     증감율_이용금액_일시불_전월  float64       0    0.0%
12      증감율_이용금액_할부_전월  float64       0    0.0%
13      증감율_이용금액_CA_전월  float64       0    0.0%
14      증감율_이용금액_체크_전월  float64       0    0.0%
15     증감율_이용금액_카드론_전월  float64       0    0.0%
16      증감율_이용건수_신용_분기  float64       0    0.0%
17      증감율_이용건수_신판_분기  float64       0    0.0%
18     증감율_이용건수_일시불_분기  float64       0    0.0%
19      증감율_이용건수_할부_분기  float64       0    0.0%
20      증감율_이용건수_CA_분기  float64       0    0.0%
21      증감율_이용건수_체크_분기  float64       0    0.0%
22     증감율_이용건수_카드론_분기  float64       0    0.0%
23      증감율_이용금액_신용_분기  float64       0    0.0%
24      증감율_이용금액_신판_분기  float64       0    0.0%
25     증감율_이용금액_일시불_분기  float64       0    0.0%
26      증감율_이용금액_할부_분기  float64       0    0.0%
27      증감율_이용금액_CA_분기  float64       0    0.0%
28      증감율_이용금액_체크_분기  float64       0    0.0%
29     증감율_이용금액_카드론_분기  float64       0    0.0%
30    잔액_신판평균한도소진율_r6m  float64       0    0.0%
31    잔액_신판최대한도소진율_r6m  float64       0    0.0%
32    잔액_신판평균한도소진율_r3m  float64       0    0.0%
33    잔액_신판최대한도소진율_r3m  float64       0    0.0%
34  잔액_신판ca평균한도소진율_r6m  float64       0    0.0%
35  잔액_신판ca최대한도소진율_r6m  float64       0    0.0%
36  잔액_신판ca평균한도소진율_r3m  float64       0    0.0%
37  잔액_신판ca최대한도소진율_r3m  float64       0    0.0%
38           변동률_일시불평잔  float64       0    0.0%
39         변동률_RV일시불평잔  float64       0    0.0%
40            변동률_할부평잔  float64       0    0.0%
41            변동률_CA평잔  float64       0    0.0%
42          변동률_RVCA평잔  float64       0    0.0%
43           변동률_카드론평잔  float64       0    0.0%
44          변동률_잔액_B1M  float64       0    0.0%
45      변동률_잔액_일시불_B1M  float64       0    0.0%
46       변동률_잔액_CA_B1M  float64       0    0.0%
47           혜택수혜율_R3M  float64  488746  20.36%
48           혜택수혜율_B0M  float64  555522  23.15%

In [ ]:
df8.shape

(2400000, 49)