### 기본 라이브러리

In [2]:
import pandas as pd
import glob
import gc

### 데이터 조회 함수

In [13]:
# 데이터 확인 함수

def get_data_spec(df):
    null_ratio = (df.isnull().mean() * 100).round(2)
    spec = pd.DataFrame({
        '변수명': df.columns,
        '데이터 타입': df.dtypes.values,
        '결측치 개수': df.isnull().sum().values,
        '결측치 비율': [f"{val}%" for val in null_ratio.values]
    })
    return spec

In [ ]:
# 호출 예시
spec_df = get_data_spec(df)

### test

#### 1.회원정보

In [ ]:
# 데이터 불러오기
df = pd.read_csv("data/test/회원정보_train.csv")

In [5]:
# 데이터 확인 함수 호출
spec_df = get_data_spec(df)
spec_df

              변수명  데이터 타입  결측치 개수 결측치 비율
0            기준년월   int64       0   0.0%
1              ID  object       0   0.0%
2          남녀구분코드   int64       0   0.0%
3              연령  object       0   0.0%
4         Segment  object       0   0.0%
..            ...     ...     ...    ...
73  우수회원면제카드수_B0M  object       0   0.0%
74    기타면제카드수_B0M  object       0   0.0%
75         카드신청건수   int64       0   0.0%
76     Life_Stage  object       0   0.0%
77      최종카드발급경과월   int64       0   0.0%

[78 rows x 4 columns]

In [8]:
df.shape

(2400000, 78)

#### 데이터 병합

In [4]:
# 1. 회원정보 데이터 병합

# 경로
path = glob.glob("./open/test/1.회원정보/*.parquet")

# 파일 병합
df_list = [pd.read_parquet(file) for file in path]
merged_df = pd.concat(df_list, ignore_index=True)

# csv로 저장
# merged_df.to_csv("data/test/1_회원정보_test.csv", index=False)
merged_df.to_parquet("data/test/1_회원정보_test.parquet", index=False)

In [5]:
# 2. 신용정보 데이터 병합

# 경로
path = glob.glob("./open/test/2.신용정보/*.parquet")

# 파일 병합
df_list = [pd.read_parquet(file) for file in path]
merged_df = pd.concat(df_list, ignore_index=True)

# csv로 저장
# merged_df.to_csv("data/test/신용정보_test.csv", index=False)
merged_df.to_parquet("data/test/2_신용정보_test.parquet", index=False)

In [6]:
# 3. 승인매출정보 데이터 병합

# 경로
path = glob.glob("./open/test/3.승인매출정보/*.parquet")

# 파일 병합
df_list = [pd.read_parquet(file) for file in path]
merged_df = pd.concat(df_list, ignore_index=True)

# csv로 저장
merged_df.to_parquet("data/test/3_승인매출정보_test.parquet", index=False)
# merged_df.to_csv("data/test/승인매출정보_test.csv", index=False)

In [7]:
# 4. 신용정보 데이터 병합

# 경로
path = glob.glob("./open/test/4.청구입금정보/*.parquet")

# 파일 병합
df_list = [pd.read_parquet(file) for file in path]
merged_df = pd.concat(df_list, ignore_index=True)

# csv로 저장
merged_df.to_parquet("data/test/4_청구입금정보_test.parquet", index=False)
# merged_df.to_csv("data/test/청구입금정보_test.csv", index=False)

In [12]:
# 5. 잔액정보 데이터 병합

# 경로
path = glob.glob("./open/test/5.잔액정보/*.parquet")

# 파일 병합
df_list = [pd.read_parquet(file) for file in path]
merged_df = pd.concat(df_list, ignore_index=True)

# csv로 저장
merged_df.to_parquet("data/test/5_잔액정보_test.parquet", index=False)
# merged_df.to_csv("data/test/잔액정보_test.csv", index=False)

In [8]:
# 6. 채널정보 데이터 병합

# 경로
path = glob.glob("./open/test/6.채널정보/*.parquet")

# 파일 병합
df_list = [pd.read_parquet(file) for file in path]
merged_df = pd.concat(df_list, ignore_index=True)

# csv로 저장
merged_df.to_parquet("data/test/6_채널정보_test.parquet", index=False)
# merged_df.to_csv("data/test/채널정보_test.csv", index=False)

In [9]:
# 7. 마케팅정보 데이터 병합

# 경로
path = glob.glob("./open/test/7.마케팅정보/*.parquet")

# 파일 병합
df_list = [pd.read_parquet(file) for file in path]
merged_df = pd.concat(df_list, ignore_index=True)

# csv로 저장
merged_df.to_parquet("data/test/7_마케팅정보_test.parquet", index=False)
#merged_df.to_csv("마케팅정보_test.csv", index=False)

In [10]:
# 8. 성과정보 데이터 병합

# 경로
path = glob.glob("./open/test/8.성과정보/*.parquet")

# 파일 병합
df_list = [pd.read_parquet(file) for file in path]
merged_df = pd.concat(df_list, ignore_index=True)

# csv로 저장
merged_df.to_parquet("data/test/8_성과정보_test.parquet", index=False)
# merged_df.to_csv("data/test/성과정보_test.csv", index=False)

#### 7. 마케팅정보

In [ ]:
# 데이터 불러오기
df = pd.read_csv("data/train/마케팅정보_train.csv")

In [ ]:
# 데이터 확인 함수 호출
spec_df = get_data_spec(df)
spec_df

                변수명  데이터 타입  결측치 개수 결측치 비율
0              기준년월   int64       0   0.0%
1                ID  object       0   0.0%
2   컨택건수_카드론_TM_B0M   int64       0   0.0%
3   컨택건수_리볼빙_TM_B0M   int64       0   0.0%
4    컨택건수_CA_TM_B0M   int64       0   0.0%
..              ...     ...     ...    ...
59     컨택건수_FDS_B0M   int64       0   0.0%
60      컨택건수_채권_R6M   int64       0   0.0%
61     컨택건수_FDS_R6M   int64       0   0.0%
62     캠페인접촉건수_R12M  object       0   0.0%
63     캠페인접촉일수_R12M  object       0   0.0%

[64 rows x 4 columns]

In [ ]:
df.shape

(2400000, 64)

#### 8. 성과정보

In [ ]:
# 데이터 불러오기
df = pd.read_csv("data/train/성과정보_train.csv")

In [ ]:
# 데이터 확인 함수 호출
spec_df = get_data_spec(df)
spec_df

                   변수명   데이터 타입  결측치 개수  결측치 비율
0                 기준년월    int64       0    0.0%
1                   ID   object       0    0.0%
2       증감율_이용건수_신용_전월  float64       0    0.0%
3       증감율_이용건수_신판_전월  float64       0    0.0%
4      증감율_이용건수_일시불_전월  float64       0    0.0%
5       증감율_이용건수_할부_전월  float64       0    0.0%
6       증감율_이용건수_CA_전월  float64       0    0.0%
7       증감율_이용건수_체크_전월  float64       0    0.0%
8      증감율_이용건수_카드론_전월  float64       0    0.0%
9       증감율_이용금액_신용_전월  float64       0    0.0%
10      증감율_이용금액_신판_전월  float64       0    0.0%
11     증감율_이용금액_일시불_전월  float64       0    0.0%
12      증감율_이용금액_할부_전월  float64       0    0.0%
13      증감율_이용금액_CA_전월  float64       0    0.0%
14      증감율_이용금액_체크_전월  float64       0    0.0%
15     증감율_이용금액_카드론_전월  float64       0    0.0%
16      증감율_이용건수_신용_분기  float64       0    0.0%
17      증감율_이용건수_신판_분기  float64       0    0.0%
18     증감율_이용건수_일시불_분기  float64       0    0.0%
19      증감율_이용건수_할부_분기  float64       0    0.0%
20      증감율_이용건수_CA_분기  float64       0    0.0%
21      증감율_이용건수_체크_분기  float64       0    0.0%
22     증감율_이용건수_카드론_분기  float64       0    0.0%
23      증감율_이용금액_신용_분기  float64       0    0.0%
24      증감율_이용금액_신판_분기  float64       0    0.0%
25     증감율_이용금액_일시불_분기  float64       0    0.0%
26      증감율_이용금액_할부_분기  float64       0    0.0%
27      증감율_이용금액_CA_분기  float64       0    0.0%
28      증감율_이용금액_체크_분기  float64       0    0.0%
29     증감율_이용금액_카드론_분기  float64       0    0.0%
30    잔액_신판평균한도소진율_r6m  float64       0    0.0%
31    잔액_신판최대한도소진율_r6m  float64       0    0.0%
32    잔액_신판평균한도소진율_r3m  float64       0    0.0%
33    잔액_신판최대한도소진율_r3m  float64       0    0.0%
34  잔액_신판ca평균한도소진율_r6m  float64       0    0.0%
35  잔액_신판ca최대한도소진율_r6m  float64       0    0.0%
36  잔액_신판ca평균한도소진율_r3m  float64       0    0.0%
37  잔액_신판ca최대한도소진율_r3m  float64       0    0.0%
38           변동률_일시불평잔  float64       0    0.0%
39         변동률_RV일시불평잔  float64       0    0.0%
40            변동률_할부평잔  float64       0    0.0%
41            변동률_CA평잔  float64       0    0.0%
42          변동률_RVCA평잔  float64       0    0.0%
43           변동률_카드론평잔  float64       0    0.0%
44          변동률_잔액_B1M  float64       0    0.0%
45      변동률_잔액_일시불_B1M  float64       0    0.0%
46       변동률_잔액_CA_B1M  float64       0    0.0%
47           혜택수혜율_R3M  float64  488746  20.36%
48           혜택수혜율_B0M  float64  555522  23.15%

In [ ]:
df.shape

(2400000, 49)